<a href="https://colab.research.google.com/github/rishugupta9621/DSMP/blob/main/data-analysis/numpy/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[49,  8, 84, 69],
       [95, 15, 46, 49],
       [58, 61, 24, 25],
       [38, 20, 22, 65],
       [42, 63, 60, 70],
       [58, 86, 93,  8]])

In [ ]:
np.sort(a)[::-1]

array([99, 93, 92, 86, 83, 48, 47, 41, 40, 31, 26, 20, 19, 13, 10])

In [ ]:
np.sort(b,axis=0)

array([[38,  8, 22,  8],
       [42, 15, 24, 25],
       [49, 20, 46, 49],
       [58, 61, 60, 65],
       [58, 63, 84, 69],
       [95, 86, 93, 70]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,100)

array([ 40,  10,  26,  92,  83,  41,  48,  47,  31,  86,  13,  99,  20,
        93,  19, 100])

In [ ]:
b

array([[49,  8, 84, 69],
       [95, 15, 46, 49],
       [58, 61, 24, 25],
       [38, 20, 22, 65],
       [42, 63, 60, 70],
       [58, 86, 93,  8]])

In [ ]:
b.shape[0]

6

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[49.,  8., 84., 69.,  1.],
       [95., 15., 46., 49.,  1.],
       [58., 61., 24., 25.,  1.],
       [38., 20., 22., 65.,  1.],
       [42., 63., 60., 70.,  1.],
       [58., 86., 93.,  8.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [41]:
# code
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [39]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [40]:
np.expand_dims(a,axis=1)

array([[40],
       [10],
       [26],
       [92],
       [83],
       [41],
       [48],
       [47],
       [31],
       [86],
       [13],
       [99],
       [20],
       [93],
       [19]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [43]:
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [45]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  4,  9, 11, 13]),)

In [46]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([40, 10, 26,  0,  0, 41, 48, 47, 31,  0, 13,  0, 20,  0, 19])

In [48]:
np.where(a%2==0,"even",'odd')

array(['even', 'even', 'even', 'even', 'odd', 'odd', 'even', 'odd', 'odd',
       'even', 'odd', 'odd', 'even', 'odd', 'odd'], dtype='<U4')

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [49]:
# code
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [50]:
np.argmax(a)

np.int64(11)

In [51]:
b

array([[49,  8, 84, 69],
       [95, 15, 46, 49],
       [58, 61, 24, 25],
       [38, 20, 22, 65],
       [42, 63, 60, 70],
       [58, 86, 93,  8]])

In [53]:
np.argmax(b,axis=0) #0--->column wise

array([1, 5, 5, 4])

In [54]:
np.argmax(b,axis=1)

array([2, 0, 1, 3, 3, 2])

In [55]:
# np.argmin
np.argmin(a)

np.int64(1)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [56]:
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [59]:
np.cumsum(a)

array([ 40,  50,  76, 168, 251, 292, 340, 387, 418, 504, 517, 616, 636,
       729, 748])

In [60]:
b

array([[49,  8, 84, 69],
       [95, 15, 46, 49],
       [58, 61, 24, 25],
       [38, 20, 22, 65],
       [42, 63, 60, 70],
       [58, 86, 93,  8]])

In [63]:
np.cumsum(b,axis=1)

array([[ 49,  57, 141, 210],
       [ 95, 110, 156, 205],
       [ 58, 119, 143, 168],
       [ 38,  58,  80, 145],
       [ 42, 105, 165, 235],
       [ 58, 144, 237, 245]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [67]:
# np.cumprod
np.cumprod(a)

array([                 40,                 400,               10400,
                    956800,            79414400,          3255990400,
              156287539200,       7345514342400,     227710944614400,
         19583141236838400,  254580836078899200, 6756758698101469184,
       6007965446062522368, 5338464272528031744, 9197100809484845056])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [70]:
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [73]:
np.percentile(a,50)

np.float64(41.0)

In [74]:
np.median(a)

np.float64(41.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [75]:
# code
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [78]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 3, 2, 1, 4, 0, 0, 0, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [79]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [80]:
# code
a


array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [98]:
items = [10,20,30,40,50,60,70,80,90,100]

a[~(np.isin(a,items))]

array([150,  96,  92,  83,  41,  48,  47,  31,  86,  13,  99,  93,  19])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [84]:
# code
a

array([40, 10, 26, 92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

In [85]:
np.flip(a)

array([19, 93, 20, 99, 13, 86, 31, 47, 48, 41, 83, 92, 26, 10, 40])

In [86]:
b

array([[49,  8, 84, 69],
       [95, 15, 46, 49],
       [58, 61, 24, 25],
       [38, 20, 22, 65],
       [42, 63, 60, 70],
       [58, 86, 93,  8]])

In [88]:
np.flip(b,axis=0)

array([[58, 86, 93,  8],
       [42, 63, 60, 70],
       [38, 20, 22, 65],
       [58, 61, 24, 25],
       [95, 15, 46, 49],
       [49,  8, 84, 69]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [91]:
# code
a

array([ 40, 150,  96,  92,  83,  41,  48,  47,  31,  86,  13,  99,  20,
        93,  19])

In [90]:
np.put(a,[1,2],[150,96])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [92]:
# code
a

array([ 40, 150,  96,  92,  83,  41,  48,  47,  31,  86,  13,  99,  20,
        93,  19])

In [93]:
np.delete(a,[0,1,2])

array([92, 83, 41, 48, 47, 31, 86, 13, 99, 20, 93, 19])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [95]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
# code
a

array([ 40, 150,  96,  92,  83,  41,  48,  47,  31,  86,  13,  99,  20,
        93,  19])

In [97]:
np.clip(a,a_min=20,a_max=80)

array([40, 80, 80, 80, 80, 41, 48, 47, 31, 80, 20, 80, 20, 80, 20])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals